import io
import plotly.graph_objects as go
import plotly.io as pio


def to_csv(df) -> bytes:
    """Convert DataFrame to CSV bytes for st.download_button."""
    buffer = io.BytesIO()
    df.to_csv(buffer, index=False)
    return buffer.getvalue()


def keyword_template_csv() -> str:
    """Return a CSV template string with example keyword rows."""
    return (
        "keyword,volume,kd\n"
        "example keyword 1,1000,25\n"
        "example keyword 2,5000,45\n"
        "example keyword 3,500,15\n"
    )


def traffic_template_csv() -> str:
    """Return a CSV template string with example traffic rows.

    Includes optional columns: revenue, transactions, aov, cr.
    """
    return (
        "date,traffic,revenue,transactions,aov,cr\n"
        "2025-01-01,10000,25000,250,100,2.5\n"
        "2025-02-01,10500,27300,260,105,2.48\n"
        "2025-03-01,11000,29700,270,110,2.45\n"
    )


def to_html_report(
    figures: list[go.Figure],
    summary_stats: dict[str, str],
    title: str = "SEO Forecast Report",
) -> str:
    """Build a self-contained HTML report with embedded Plotly charts.

    Args:
        figures: List of Plotly figures to embed.
        summary_stats: Dict of stat name -> formatted value for the summary section.
        title: Report title.

    Returns:
        Complete HTML string.
    """
    # Build summary cards HTML
    cards_html = ""
    for stat_name, stat_value in summary_stats.items():
        cards_html += f"""
        <div style="background:#F8FAFC;border-radius:8px;padding:16px 24px;
                     min-width:180px;text-align:center;border:1px solid #E2E8F0;">
            <div style="font-size:13px;color:#64748B;margin-bottom:4px;">{stat_name}</div>
            <div style="font-size:22px;font-weight:700;color:#0F172A;">{stat_value}</div>
        </div>
        """

    # Build chart HTML
    charts_html = ""
    for fig in figures:
        chart_div = pio.to_html(fig, full_html=False, include_plotlyjs=False)
        charts_html += f'<div style="margin:24px 0;">{chart_div}</div>'

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
            max-width: 1200px; margin: 0 auto; padding: 24px;
            background: #FFFFFF; color: #0F172A;
        }}
        h1 {{ color: #2563EB; border-bottom: 2px solid #E2E8F0; padding-bottom: 12px; }}
        .summary {{ display: flex; gap: 16px; flex-wrap: wrap; margin: 24px 0; }}
    </style>
</head>
<body>
    <h1>{title}</h1>
    <div class="summary">{cards_html}</div>
    {charts_html}
    <footer style="margin-top:40px;padding:16px 0;border-top:1px solid #E2E8F0;
                    color:#94A3B8;font-size:12px;">
        Generated by SEO Traffic & Revenue Forecasting Engine
    </footer>
</body>
</html>"""
    return html
